sudo: required

services:
  - docker

env:
  matrix:
    - DOCKER_VERSION=1.11.2
    - DOCKER_VERSION=1.12.0

before_install:
  # check what version of docker is installed beforehand
  - dpkg -l | grep docker
  # install the version of docker in the DOCKER_VERSION env var
  - ./.travis.sh install_docker
  # double-check that the version/config is correct
  - ./.travis.sh dump_docker_config
  - docker version
  - docker info

script:
  - ./gradlew assemble
  - ./gradlew check --debug --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./.travis.sh publish_to_bintray

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: java

jdk:
  - oraclejdk7
  - oraclejdk8
